"""Detect Flatpak applications installed on the system."""

from __future__ import annotations

import os
import re
import subprocess

from backend import paths
from data.app_registry import AppEntry

_FLATPAK_ID = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_.-]+")
_ICON_SIZES = ("scalable", "256x256", "128x128", "64x64", "48x48")


def get_installed_flatpaks() -> list[AppEntry]:
    """Return AppEntry instances for every Flatpak whose data folder exists."""
    try:
        result = subprocess.run(
            ["flatpak", "list", "--app", "--columns=application,name"],
            capture_output=True, text=True, timeout=10, check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return []  # Flatpak is optional; without it there is nothing to list.
    if result.returncode != 0:
        return []

    apps: list[AppEntry] = []
    seen: set[str] = set()
    for line in result.stdout.splitlines():
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        app_id, name = parts[0].strip(), parts[1].strip()
        if not _FLATPAK_ID.fullmatch(app_id) or app_id in seen:
            continue
        seen.add(app_id)

        base = paths.expand(f"~/.var/app/{app_id}")
        if not os.path.isdir(base):
            continue
        # cache/ is volatile and regenerated by the app; back up the whole
        # per-app folder only when neither config/ nor data/ exists.
        config_paths = [p for p in (os.path.join(base, "config"), os.path.join(base, "data"))
                        if os.path.isdir(p)] or [base]

        apps.append(AppEntry(
            app_id=f"flatpak-{app_id}",
            name=f"{name or app_id} (Flatpak)",
            icon=_resolve_flatpak_icon(app_id),
            binary="flatpak",
            category="flatpak",
            config_paths=config_paths,
            process_name=app_id,
            sensitive=True,  # Dynamic app data may include credentials/documents.
            reset_paths=[os.path.join(base, "config")],  # Keep data/ and installed environments.
        ))
    return apps


def _resolve_flatpak_icon(app_id: str) -> str:
    """The icon file exported by the Flatpak, or its ID for the icon theme."""
    for base in (
        "/var/lib/flatpak/exports/share/icons",
        os.path.join(paths.xdg_home("XDG_DATA_HOME", ".local/share"), "flatpak/exports/share/icons"),
    ):
        for size in _ICON_SIZES:
            for ext in (".svg", ".png"):
                path = os.path.join(base, "hicolor", size, "apps", app_id + ext)
                if os.path.isfile(path):
                    return path
    return app_id
